### ISSUE TITLE
Multiple revisions are available [abc, abc]

### ISSUE THREAD

**Issue by gorshkov-leonid** [theia-ide/yang-lsp#127]
There is a warning "Multiple revisions are available [abc, abc]" appeared if it is exists in several folders. But in case when file copied to working folder (for example target folder in maven project) it should be skipped.  How to exclude folder from file watcher?

**Comment by JanKoehnlein** [comment]
We currently don't have a config to exclude folders, as it's likely to be different for different clients (Theia, VSCode, Eclipse). We could add something in the `yang.settings` file. 

Which client are you using?
Are you using YANG along with Maven?

**Comment by gorshkov-leonid** [comment]
It is another isuue :) but I think excluded pathes shoul be related to root folder and shoul not depend on clients

**Comment by JanKoehnlein** [comment]
I was referring to clients because I've seen this (and have been annoyed by it) in the Eclipse version as well, where JDT automatically copies the YANG files from source folders to the respective binary folders. In your case, it's not the client but Maven. The essence is, it is not caused by the language server but by external tools/clients duplicating files somewhere below the same root/project/workspace folders. 

I am not aware of any semantics on paths in YANG but I'd expect users to have YANG files that should be aware of each other in different directories in the same workspace. So just processing YANG files in the rootDir/workspace folder doesn't seem to be an option. 

As the location of the duplicates depends on external tools or clients, we cannot solve this generically in the LS, So I'd propose to add an exclusion pattern to the `yang.settings`, such that every user can adapt it to the remaining tools in their chains.

**Comment by gorshkov-leonid** [comment]
I agree.. any way to pass settings (cli arguments, settings file) it is acceptable to us.

**Comment by JanKoehnlein** [comment]
The property `excludePath` in the `yang.settings` JSON file can now point to a colon separated list of excluded directories, e.g.

    {
       "excludePath": "build/classes:bin/foo" 
    }

Path separator is always `/`

**Comment by gorshkov-leonid** [comment]
Thank you!!!

**Comment by JanKoehnlein** [comment]
PS: Are you using [yangster](https://github.com/theia-ide/yangster) or just the yang-lsp in Che? The former is a Theia extension which also provides graphical views on your model. Theia is going to be the new IDE technology of Che, so this will come to you for free sooner or later.
