### ISSUE TITLE
There is no need to report 'Multiple revision are available' as a WARNING

### ISSUE THREAD

**Issue by huyuwen** [theia-ide/yang-lsp#99]
https://github.com/theia-ide/yang-lsp/blob/a14aaabbdebf58083e5cf25cc557f2e1f0be7686/yang-lsp/io.typefox.yang/src/main/java/io/typefox/yang/scoping/ScopeContextProvider.xtend#L423

In RFC7950, "Allow imports of multiple revisions of a module." There has such a change.
So I don't think it is worth to report multiple revisions as Warning, maybe log it at backend is good enough.

**Comment by JanKoehnlein** [comment]
I understand "Allow imports of multiple revisions of a module." in the way that within one module you can import multiple revisions of another module. Of course then you have to specify which revisions. If I get it correctly, the warning is about something different: If you don't specify a revision on a single import while there are multiple revisions available, you should rather add one, as otherwise the import is ambiguous.

Does that make sense?

**Comment by huyuwen** [comment]
I discussed with our Yang module expert. From yang spec RFC 7950 persective, revision is just a kind of history of module changes. Practically, only latest revision (with latest date) need to be considered.
On the other side, according to RFC 7950, revision is an optional substatement of import. So if there is no revision is present inside an import. Practically, the latest revision is used usually.

Of cause, we also discussed such a potential error case. Considering, there are two module A file, in the same scope context, for instance module-A.yang and module-A@2017-10-10.yang. If the two module A files are actually have the same latest revisions. In this case, two resources point to one module instance.
That should be the real warning for ambiguous.

**Comment by JanKoehnlein** [comment]
I see. https://github.com/theia-ide/yang-lsp/pull/100

Should we issue a warning when a module defines multiple revisions and is imported with a revision that is not the most recent one in the file?

**Comment by huyuwen** [comment]
HI Jan,

Sorry to reply you late.
Yes, that's a good proposal, please do that.

Thanks a lot.

**Comment by JanKoehnlein** [comment]
Fixed
